# Generated by Django 4.2.5 on 2023-09-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='system',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
